### ISSUE TITLE
Add Github icon

### ISSUE THREAD

**Issue by polubis** [polubis/WebBlog#128]
**Context** 

We want to link in Footer our repository. Add a link with GithubIcon in the following way:

![Image](https://user-images.githubusercontent.com/22937810/231822359-7c5b724d-e815-4702-aaa1-f2bff193baa6.png)

**Definition of done**

1. Icon is added near LinkedinIcon.
2. Looks good.
3. After clicking the icon user opens -> https://github.com/polubis/WebBlog/tree/develop in a new tab.

**Comment by kmilek73** [comment]
https://github.com/polubis/WebBlog/compare/main...128
