### ISSUE TITLE
Add next and previous article buttons

### ISSUE THREAD

**Issue by polubis** [polubis/WebBlog#57]
# Context

As a user, I want to see 2 buttons at the bottom of the article page (**Previous** and **Next**).

# Acceptance criteria
1. If there is no next article -> there is no **Next** button displayed.
2. If there is no previous article -> there is no button **Previous** displayed.
3. In any other case we're displaying both buttons.
4. After clicking the **Next** button user is moved to the next article (you can check the order in the home page timeline).
5. After clicking the **Previous** button the user is moved to the previous article (you can check the order in the home page timeline).

This should look the same as on the current **Lesson** page:

![Image](https://user-images.githubusercontent.com/22937810/226959026-3fac205b-42b4-4509-856c-686bfacc8b81.png)

New components can be created and used in two places.

Here is a link to the Lesson page: https://incandescent-faun-b88398.netlify.app/courses/react-hooks-spellbook/events/use-clipboard/

# Test scenarios

1. As a user I want to see only one button **Next** at the bottom of the first article page
- Go to the article page
- Click the button which opens the first article
- It should be only the **Next** button at the bottom of the page
- Click the **Next** button
- It should move to the next article

2. As a user I want to see only one button **Previous** at the bottom of the last article page
- Go to the article page
- Click the button which opens the last article
- It should be only the **Previous** button at the bottom of the page
- Click the **Previous** button
- It should move to the previous article

3. As a user I want to see 2 buttons at the bottom of the article page (**Previous** and **Next**)
- Go to the article page
- Click the button which opens the article (except the first and last article)
- It should be two buttons at the bottom of the page
- Click the **Next** button, it should move to the next article
- Click the **Previous** button, it should move to the previous article

**Comment by polubis** [comment]
@klaudiazalewska PR is here you can start testing that:
https://github.com/polubis/WebBlog/pull/94

**Comment by klaudiazalewska** [comment]
Everything works well, but I have found one bug:

1. When I go to one of the courses, the page's name is white, it should be coloured.
_How it is right now:_


![Image](https://user-images.githubusercontent.com/73396554/231736540-c844cfb6-8ffa-49f8-9791-5c514f27814c.png)


![Image](https://user-images.githubusercontent.com/73396554/231736731-6ba3cc9e-fdf5-4d2e-ab62-bf7cd947ab37.png)


_How it should be:_
It should be coloured.
