### ISSUE TITLE
Increase authors model

### ISSUE THREAD

**Issue by polubis** [polubis/WebBlog#66]
**Context**

Check **authors.json** file - here we have all author's data. There should be additional properties added which will describe the projects which the dedicated author had. It can be name, described, role, and start/end date.

TypeScript definitions must be also accepted for authors to guarantee Type-Safety.

**Acceptance criteria**

1. There is no regression in **/authors** page.
2. TypeScript definitions are updated.
3. New properties are added **authors.json**.

**Comment by kmilek73** [comment]
[
  {
    "id": "polubis",
    "name": "polubis",
    "firstName": "Adrian",
    "lastName": "Połubiński",
    "role": "Senior Frontend Developer",
    "bio": "Software development and application design are more than just a job for me. I have been a freelancer for a few years and I carried out projects in various technologies. Focused on React, TypeScript, NodeJS. In my free time, I play guitar.",
    "githubURL": "https://github.com/polubis",
    "linkedinURL": "https://www.linkedin.com/in/adrian-po%C5%82ubi%C5%84ski-281ab2172/",
    "projects": 
    [
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      }
    ]

  },
      
    
  {
    "id": "awęgrodzki",
    "name": "awęgrodzki",
    "firstName": "Artur",
    "lastName": "Węgrodzki",
    "role": ".NET developer",
    "bio": "Daily working in C# and .NET environments. Specialized in Backend APIs, Xamarin mobile applications and databases. In my free time, I ride a bike and play games.",
    "linkedinURL": "https://www.linkedin.com/in/artur-w%C4%99grodzki-926109194/",
    "projects": 
    [
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      }
    ]
  },
  {
    "id": "kreszko",
    "name": "kreszko",
    "firstName": "Krzysztof",
    "lastName": "Reszko",
    "role": "Editor & Reviewer",
    "bio": "English teacher. In the meantime, I do translation and editing work. My Interests are fitness and video games.",
    "projects": 
    [
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      }
    ]
  },
  {
    "id": "kwozniak",
    "name": "kwozniak",
    "firstName": "Kacper",
    "lastName": "Woźniak",
    "role": "Frontend developer",
    "bio": "Professionally - frontend developer focused on React, Vue and Typescript. I am happy to engage in additional activities related to programming. Privately - motorization enthusiast.",
    "githubURL": "https://github.com/ajronn",
    "linkedinURL": "https://www.linkedin.com/in/ajronn/",
    "projects": 
    [
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      }
    ]
  },
  {
    "id": "pjurczyk",
    "name": "pjurczyk",
    "firstName": "Patryk",
    "lastName": "Jurczyk",
    "role": "Frontend developer",
    "bio": "The technologies I develop are React and TypeScript. I like to take on more and more difficult things because with them I can learn the most. I spend my free time actively at the gym or cycling.",
    "githubURL": "https://github.com/PatrykJurczyk",
    "linkedinURL": "https://www.linkedin.com/in/patryk-jurczyk-832311241/",
    "projects": 
    [
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      }
    ]
  },
  {
    "id": "kzalewska",
    "name": "kzalewska",
    "firstName": "Klaudia",
    "lastName": "Zalewska",
    "role": "Junior Q&A",
    "bio": "I have a foundation in programming and JavaScript, which helps me ensure software quality and create seamless user experiences. Outside of work, I enjoy reading criminal books.",
    "githubURL": "https://github.com/klaudiazalewska",
    "linkedinURL": "https://www.linkedin.com/in/klaudia-zalewska-725902231/",
    "projects": 
    [
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      },
      {
      "tittle": "Creating a CRM for companies selling heat pumps",
      "taskProject": "Creating Creation of the Client module",
      "taskDescription":"FrontEnd: Creating a Customer panel along with CRUD operations. Backend: Creating a controller, model and endPionts, export to JSON",
      "startProject": "2023.01.01",
      "durationProject": "in progress.. or 2 weeks ",
      "stack": "React, Bootstrap, Node, Express, MonagoDB",
      "linkToProject": "www.link.com",
      "linkToCodeTaskProject": "https://github.com/kmilek73/java_start"
      }
    ]
  }
]
