### ISSUE TITLE
Add option to see source code for code snippets

### ISSUE THREAD

**Issue by polubis** [polubis/WebBlog#70]
**Context**

Add a new button that allows the user to go to the snippet source. Snippet should be opened in a new tab after clicking the dedicated button which will be called "Source".

![Image](https://user-images.githubusercontent.com/22937810/230439549-126de8a7-7615-491e-99a0-915439e9ed24.png)

**Acceptance criteria**

1. There is no regression in the code snippet component.
2. New tab is opened after clicking the button in the code snippet which is called "Source".
3. Button looks correctly as designed in Figma - also looks good on **mobile/tablet/desktop**.

**Comment by polubis** [comment]
@klaudiazalewska please check it on develop branch

**Comment by klaudiazalewska** [comment]
I have checked it. Everything looks good.
